#!/bin/bash
# This script downloads the latest tzdata files from ftp.iana.org and puts them
# in the tzdata directory, overwriting the existing ones.
# We do not need all the files, so we delete the ones we do not use.
mkdir -p tzdata/       \
  && cd tzdata/        \
  && wget 'ftp://ftp.iana.org/tz/tzdata-latest.tar.gz' \
  && tar -zxvf tzdata-latest.tar.gz                    \
  && rm tzdata-latest.tar.gz                           \
  && rm factory leap-seconds.* leapseconds leapseconds.* Makefile iso3166.tab README systemv yearistype.sh zone.tab zone1970.tab backzone checktab.awk CONTRIBUTING NEWS Theory zoneinfo2tdf.pl
